//
// This file was generated by the JPA Modeler
//
package entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author frastie
 */
@Entity
public class Stockoperation implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private double currentq;

    @Basic
    @Temporal(TemporalType.DATE)
    private Date timestamp;

    @Basic
    private double loaded_quantity;

    @Basic
    private double downloaded_quantity;

    @Basic
    private String notes;

    @ManyToOne(targetEntity = Item.class)
    private Item item;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public double getCurrentq() {
        return this.currentq;
    }

    public void setCurrentq(double currentq) {
        this.currentq = currentq;
    }

    public Date getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public double getLoaded_quantity() {
        return this.loaded_quantity;
    }

    public void setLoaded_quantity(double loaded_quantity) {
        this.loaded_quantity = loaded_quantity;
    }

    public double getDownloaded_quantity() {
        return this.downloaded_quantity;
    }

    public void setDownloaded_quantity(double downloaded_quantity) {
        this.downloaded_quantity = downloaded_quantity;
    }

    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Item getItem() {
        return this.item;
    }

    public void setItem(Item item) {
        this.item = item;
    }

}
