//
// This file was generated by the JPA Modeler
//
package entities;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * @author frastie
 */
@Entity
public class Stockoperation implements Serializable {

    @Transient
    private PropertyChangeSupport changeSupport = new PropertyChangeSupport(this);

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private double currentq;

    @Basic
    @Temporal(TemporalType.DATE)
    private Date timestamp;

    @Basic
    private double loaded_quantity;

    @Basic
    private double downloaded_quantity;

    @Basic
    private String notes;

    @ManyToOne(targetEntity = Item.class)
    private Item item;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        Long oldId = this.id;
        this.id = id;
        changeSupport.firePropertyChange("id", oldId, id);
    }

    public double getCurrentq() {
        return this.currentq;
    }

    public void setCurrentq(double currentq) {
        double oldCurrentq = this.currentq;
        this.currentq = currentq;
        changeSupport.firePropertyChange("currentq", oldCurrentq, currentq);
    }

    public Date getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Date timestamp) {
        Date oldTimestamp = this.timestamp;
        this.timestamp = timestamp;
        changeSupport.firePropertyChange("timestamp", oldTimestamp, timestamp);
    }

    public double getLoaded_quantity() {
        return this.loaded_quantity;
    }

    public void setLoaded_quantity(double loaded_quantity) {
        double oldLoaded_quantity = this.loaded_quantity;
        this.loaded_quantity = loaded_quantity;
        changeSupport.firePropertyChange("loaded_quantity", oldLoaded_quantity, loaded_quantity);
    }

    public double getDownloaded_quantity() {
        return this.downloaded_quantity;
    }

    public void setDownloaded_quantity(double downloaded_quantity) {
        double oldDownloaded_quantity = this.downloaded_quantity;
        this.downloaded_quantity = downloaded_quantity;
        changeSupport.firePropertyChange("downloaded_quantity", oldDownloaded_quantity, downloaded_quantity);
    }

    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        String oldNotes = this.notes;
        this.notes = notes;
        changeSupport.firePropertyChange("notes", oldNotes, notes);
    }

    public Item getItem() {
        return this.item;
    }

    public void setItem(Item item) {
        Item oldItem = this.item;
        this.item = item;
        changeSupport.firePropertyChange("item", oldItem, item);
    }

    public void addPropertyChangeListener(PropertyChangeListener listener) {
        changeSupport.addPropertyChangeListener(listener);
    }

    public void removePropertyChangeListener(PropertyChangeListener listener) {
        changeSupport.removePropertyChangeListener(listener);
    }

}
